export * from './tables/user.ts'
export * from './tables/authors.table.ts'
export * from './tables/books.table.ts'
export * from './tables/genre.table.ts'
export * from './tables/category.table.ts'
export * from './tables/curses.table.ts'
export * from './tables/professor.table.ts'
