export * from '@/infrastructure/routes/auth.router.ts'
export * from '@/infrastructure/routes/authors.router.ts'
export * from '@/infrastructure/routes/category.router.ts'
export * from '@/infrastructure/routes/curse.router.ts'
export * from '@/infrastructure/routes/genre.router.ts'
export * from '@/infrastructure/routes/professor.router.ts'
export * from '@/infrastructure/routes/user.router.ts'
export * from '@/infrastructure/routes/books.router.ts'
