export * from '@/infra/routes/auth.router.ts'
export * from '@/infra/routes/authors.router.ts'
export * from '@/infra/routes/category.router.ts'
export * from '@/infra/routes/curse.router.ts'
export * from '@/infra/routes/genre.router.ts'
export * from '@/infra/routes/professor.router.ts'
export * from '@/infra/routes/user.router.ts'
export * from '@/infra/routes/books.router.ts'
